import { matchesAnyGlob } from "./path-utils.ts"
import type { PolicyDecision } from "./types.ts"

interface GeneratedRule {
 readonly glob: string
 readonly kind: "deny" | "ask"
 readonly redirectHint: string
}

/**
 * Files that are produced by some other source. Editing them is almost always
 * wrong — the agent should edit the source/template instead.
 */
export const GENERATED_RULES: ReadonlyArray<GeneratedRule> = [
 { glob: "**/*.generated.ts", kind: "deny", redirectHint: "edit the generator/template that produces this .generated.ts file (often a sibling .gen.ts, codegen config, or schema)." },
 { glob: "**/*.generated.js", kind: "deny", redirectHint: "edit the generator/template, not the .generated.js output." },
 { glob: "**/*.generated.d.ts", kind: "deny", redirectHint: "edit the source schema/types — .generated.d.ts is regenerated." },
 { glob: "**/dist/**", kind: "deny", redirectHint: "edit the source under src/, then rebuild." },
 { glob: "**/build/**", kind: "deny", redirectHint: "edit the source files; build/ is produced by the build step." },
 { glob: "**/node_modules/**", kind: "deny", redirectHint: "do not edit node_modules; patch via package.json/patch-package or upstream." },
 { glob: "**/__generated__/**", kind: "deny", redirectHint: "edit the GraphQL/codegen schema, not the __generated__ output." },
 { glob: "**/*.pb.ts", kind: "deny", redirectHint: "edit the .proto file; .pb.ts is regenerated by protoc." },
 { glob: "**/*.pb.go", kind: "deny", redirectHint: "edit the .proto file; .pb.go is regenerated by protoc." },
 { glob: "**/openapi-generated/**", kind: "deny", redirectHint: "edit the OpenAPI spec; openapi-generated/ is regenerated." },
 { glob: "**/prisma/client/**", kind: "deny", redirectHint: "edit prisma/schema.prisma and run `prisma generate`." },
 { glob: "**/prisma/migrations/**", kind: "ask", redirectHint: "prefer creating a new migration via `prisma migrate dev` rather than editing existing migration SQL." },
 { glob: "**/.next/**", kind: "deny", redirectHint: "edit pages/components; .next/ is the Next.js build output." },
 { glob: "**/.turbo/**", kind: "deny", redirectHint: ".turbo/ is the Turbo cache; do not edit." },
 { glob: "**/coverage/**", kind: "deny", redirectHint: "coverage/ is generated by the test runner." },
]

export const evaluateGeneratedFile = (filePath: string): PolicyDecision => {
 for (const rule of GENERATED_RULES) {
 if (matchesAnyGlob(filePath, [rule.glob]) !== undefined) {
 if (rule.kind === "deny") {
 return {
 kind: "deny",
 reason: `${filePath} matches generated-file pattern ${rule.glob}; ${rule.redirectHint}`,
 suggested: rule.redirectHint,
 }
 }
 return {
 kind: "ask",
 reason: `${filePath} matches generated-file pattern ${rule.glob}; ${rule.redirectHint}`,
 }
 }
 }
 return { kind: "passthrough" }
}
