export const HOOK_EVENT_NAMES = [
  "SessionStart",
  "UserPromptSubmit",
  "UserPromptExpansion",
  "PreToolUse",
  "PostToolUse",
  "PostToolUseFailure",
  "PostToolBatch",
  "Stop",
  "PreCompact",
  "PostCompact",
  "SessionEnd",
  "PermissionRequest",
  "ConfigChange",
  "FileChanged",
  "SubagentStart",
  "SubagentStop",
  "TaskCreated",
  "TaskCompleted",
  "Setup",
  "PermissionDenied",
  "StopFailure",
  "TeammateIdle",
  "Notification",
  "InstructionsLoaded",
  "CwdChanged",
  "WorktreeCreate",
  "WorktreeRemove",
  "Elicitation",
  "ElicitationResult",
] as const

export type HookEventName = (typeof HOOK_EVENT_NAMES)[number]
